POST http://localhost:4000/api/mpesa/stk-push
Content-Type: application/json

{
  "phoneNumber": "0790626558",
  "amount": 1000,
  "accountReference": "Order123",
  "transactionDesc": "Testing STK Push"
}
