import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Layout from "./ui/layout";
import { Toaster } from "sonner";
import {
  ClerkProvider
} from "@clerk/nextjs";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Alphatech & Robotics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <ClerkProvider>
          <Layout>
            <Toaster richColors position="top-right" />
            {children}
          </Layout>
        </ClerkProvider>
      </body>
    </html>
  );
}
